---

- name: install > Unarchive
  unarchive:
    src:     ffmpeg-2.6.3-64bit-static.tar.xz
    dest:    /opt
    creates: /opt/ffmpeg-2.6.3-64bit-static

- name: install > Link to ffmpeg binary
  file:
    src:   /opt/ffmpeg-2.6.3-64bit-static/ffmpeg
    dest:  "{{ elao_ffmpeg_bin }}"
    state: link

- name: install > Link to ffprobe binary
  file:
    src:   /opt/ffmpeg-2.6.3-64bit-static/ffprobe
    dest:  "{{ elao_ffmpeg_ffprobe_bin }}"
    state: link
